### PR TITLE
put respawn in cfg

### PR DESCRIPTION
**Pull request by jiyinyiyong**
Related https://github.com/fgnass/node-dev/issues/104

### CODE REVIEW

**Comment by fgnass** [comment]
Shouldn't this also be added here? https://github.com/fgnass/node-dev/blob/master/bin/node-dev#L20

**Comment by fgnass** [comment]
We also need a basic test case in order to merge this

**Comment by jiyinyiyong** [comment]
I may need help working on the test. I suppose it's this but not sure how it works:
```js
test('should restart when a file is touched', function(t) {
  spawn('log.js --respawn', function(out) {
    if (out.match(/touch message.js/)) {
      setTimeout(touchFile(), 500)
      return function(out) {
        if (out.match(/Restarting/)) {
          return { exit: t.end.bind(t) }
        }
      }
    }
  })
})
```

and `npm test` always gives failing message below with or without my code:

```
➤➤ npm test

> node-dev@2.7.1 test /Users/chen/repo/jiyinyiyong/node-dev
> tap test/*.js

test/index.js ....................................... 15/17 30s
  not ok timeout
  not ok missing plan
    results:
      ok: false
      count: 14
      pass: 13
      fail: 1
      failures:
        - ok: false
          id: 14
          name: timeout
          parent: ''

total ............................................... 15/17


  15 passing (30s)
  2 failing

npm ERR! Test failed.  See above for more details.
```

**Comment by ashelley** [comment]
Hello, I'm looking for node-dev to respawn on crash but this patch does not fix my issue.  Here is my test code:

```
var http = require('http');
var requestListener = function (req, res) {
  res.writeHead(200);
  res.end('Hello, World!\n');
}

process.on('uncaughtException', function(err) {
  console.log('Caught exception: ' + err, err.stack);
  //give server some time to die gracefully in production
  setTimeout(function() {
  	process.exit(1);
  }, 1000);
});

var server = http.createServer(requestListener);
server.listen(process.env.PORT || 3000);

//simulate a server crash
setTimeout(function() {
	throw new Error('Your server has just crashed');
}, 5000);
```

Here is my result
```
$ node-dev --respawn app
Error: Your server has just crashed
    at null._onTimeout (C:\inetpub\wwwroot\node-dev-test\app.js:20:8)
    at Timer.listOnTimeout (timers.js:119:15)
Caught exception: Error: Your server has just crashed Error: Your server has just crashed
    at null._onTimeout (C:\inetpub\wwwroot\node-dev-test\app.js:20:8)
    at Timer.listOnTimeout (timers.js:119:15)
[ERROR] 16:05:10 Error
```

Result: server doesn't restart.
Expected: result: server restarts after one second.

**Comment by jiyinyiyong** [comment]
`node-dev` does not respawn on crash, it repawns on file changes

**Pull request merged**
