### PR TITLE
Refactor CLI argument parsing

### PR DESCRIPTION
**Pull request by gasi**
I originally built this to support `--ignore path1,path2` CLI option for #99, but then realized CLI options  didn’t get passed to `wrap.js`, so I made the change without this. Nonetheless, this uses one of the most popular CLI argument parsers which will enable easier adding of new options in the future.

Enjoy!

/cc @aseemk

### CODE REVIEW

**Comment by fgnass** [comment]
Awesome, I wanted to to do something similar since ages! I've added you as collaborator as well as module owner on npm. I currently don't have the time to cut a new release, so it would be rad if you cut do it.

**Comment by gasi** [comment]
@fgnass Thank you for the quick reply on this, accepting my changes, and making me a collaborator — _With great power comes great responsibility._ :smile: I will cut a new release and push to npm :+1:

**Comment by gasi** [comment]
@fgnass I added some tests, cut 2.7.0 and published it to npm: https://github.com/fgnass/node-dev/releases/tag/2.7.0 :smiley:

**Comment by fgnass** [comment]
@gasi thank you so much! Ignoring files was one of the most requested features from the beginning of this project. I didn't like the idea in the first place because it somehow violates node-dev's _zero-conf_ philosophy but I don't see any better solution for universal/isomorphic apps. I'm really glad you jumped in to help me maintain this project. Thanks again for your awesome work.

**Comment by aseemk** [comment]
Woot @gasi!

**Pull request merged**
