### PR TITLE
Allow passing --no-warnings on to node process

### PR DESCRIPTION
**Pull request by lehni**
to hide warnings about experimental-loader / experimental-modules

### CODE REVIEW

**Comment by bjornstar** [comment]
Could you add this to the list of known [node command-line arguments](https://github.com/fgnass/node-dev/blob/master/lib/cli.js#L13)?

I'd prefer to pass this on rather than hiding warnings when people aren't expecting that.

**Comment by lehni** [comment]
That makes sense. I tried to pass it first but I didn't make it through. And I was also under the impression that it needs to come before the loader argument, or it won't be effective there, but maybe I'm wrong. I'll spend more time on this tomorrow.

**Comment by lehni** [comment]
@bjornstar I've adjusted this now. I needed to change from`unshift()` to `push()` for the `--experimental` / `--loader` args, because they need to come after `--no-warnings` to have an effect.

**Comment by lehni** [comment]
Argh this is actually not working. I spent a while trying to understand what's wrong, and there are two problems:

- `minimist()` turns `--no-warnings` into `warnings: false` and this does not work with the rest of the arguments handling that I am currently having a hard time to make sense out of (things like  `nodeArgsReducer()`, `unknownFactory()`, it's all quite obscure to me).

- `ushift()` was needed because these arguments need to come before the scripts!

**Comment by lehni** [comment]
The part that turns everything upside down is here: 

https://github.com/substack/minimist/blob/7efb22a518b53b06f5b02a1038a88bd6290c2846/index.js#L118-L120

Sadly this behavior can't be turned off.

**Comment by bjornstar** [comment]
> Argh, this is actually not working yet. I spent a while trying to understand what's wrong, and there are two problems:
> 
> * `minimist()` turns `--no-warnings` into `warnings: false` and this does not work with the rest of the arguments handling that I am currently having a hard time to make sense out of (things like  `nodeArgsReducer()`, `unknownFactory()`, it's all quite obscure to me).
> * `unshift()` was needed because these arguments need to come before the scripts!

node does a lot of custom argument parsing so it's quite challenging to replicate their behavior. We use nodeOptional to pull the known node arguments off of argv and handle them ourselves instead of passing them to minimist. Originally it was because they have optional values which minimist does not support hence the name optional. We can change the name to something better.

**Comment by bjornstar** [comment]
I went ahead and implemented it, i'll get a release out shortly. Thanks for the contributions!

**Comment by lehni** [comment]
Happy to help where I can! Thank you for the fast responses!

**Pull request closed without merging**
