### PR TITLE
support unknown options

### LINKED ISSUE #102: 2.7.0 broke.
now it don't support `--harmony`, `--debug-brk`, `--debug`

### PR DESCRIPTION
**Pull request by atian25**
fixed #102

### CODE REVIEW

**Comment by atian25** [comment]
`node-dev es6.js --harmony`  works
`node-dev es6.js --harmony --dedupe` works
`node-dev --harmony --dedupe es6.js` works

but `node-dev --harmony es6.js` will not run commander,  due to commander parse, can fixed by replace `process.argv`, but I don't know if need to do this.

**Comment by fgnass** [comment]
Calling `node-dev es6.js --harmony` must pass the `--harmony` argument as argv to the script, not to the node binary. `node-dev --harmony es6.js` is the one that needs to work.

**Comment by fgnass** [comment]
I'll take a look at this.

**Comment by atian25** [comment]
@fgnass

currently `commander` will not pass argument as argv to the script.
ok, I'm working at it

**Comment by fgnass** [comment]
We now have a working version at https://github.com/fgnass/node-dev/tree/minimist

**Comment by fgnass** [comment]
Just need to add back the usage info output if no script is specified

**Comment by atian25** [comment]
cool

**Comment by fgnass** [comment]
2.7.1 now correctly handles node/v8 options again.

**Pull request closed without merging**
